import { useState } from "react";
import {
  analyzeGitLog,
  REPORT_SCHEMA_VERSION,
  type BusfactorReport,
} from "bus-lib";
import { CommitStatsTable } from "./components/CommitStatsTable.js";
import { ReportSections } from "./components/ReportSections.js";
import { ReportSummary } from "./components/ReportSummary.js";
import { UploadPanel } from "./components/UploadPanel.js";
import { readGitLogFile } from "./lib/file-upload.js";

const getErrorMessage = (error: unknown): string =>
  error instanceof Error
    ? error.message
    : "Could not analyze the uploaded file.";

export const App = () => {
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [fileName, setFileName] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [report, setReport] = useState<BusfactorReport | null>(null);

  const handleFileSelected = (file: File | null): void => {
    setErrorMessage(null);
    setFileName(file?.name ?? null);
    setReport(null);
    setIsLoading(true);

    void readGitLogFile(file)
      .then((text) => {
        const nextReport = analyzeGitLog(text, {
          source: {
            mode: "git-log",
            label: file?.name,
          },
        });

        if (nextReport.authors.length === 0) {
          throw new Error(
            "No commits were found. Upload git log text generated by git log --no-merges --name-status main.",
          );
        }

        setReport(nextReport);
      })
      .catch((error: unknown) => {
        setErrorMessage(getErrorMessage(error));
      })
      .finally(() => {
        setIsLoading(false);
      });
  };

  return (
    <main>
      <header>
        <h1>Busfactor2</h1>
        <p>
          Upload a prepared git log to analyze commit activity and file
          ownership.
        </p>
      </header>

      <UploadPanel
        errorMessage={errorMessage}
        fileName={fileName}
        hasReport={report !== null}
        isLoading={isLoading}
        onFileSelected={handleFileSelected}
      />

      {report !== null ? (
        <>
          <ReportSummary report={report} />
          <CommitStatsTable report={report} />
          <ReportSections report={report} />
        </>
      ) : null}

      <footer>
        <small>Schema: {REPORT_SCHEMA_VERSION}</small>
      </footer>
    </main>
  );
};
