import { fireEvent, render, screen, within } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { REPORT_SCHEMA_VERSION } from "bus-lib";
import legacyGitLog from "../../bus-lib/test/fixtures/legacy-git-log.txt?raw";
import { App } from "./App.js";

const uploadGitLog = (contents: string, name = "legacy-git-log.txt") => {
  render(<App />);

  const input = screen.getByLabelText("Git log file");
  const file = new File([contents], name, { type: "text/plain" });

  fireEvent.change(input, {
    target: {
      files: [file],
    },
  });
};

const getSection = (name: string): HTMLElement => {
  const heading = screen.getByRole("heading", { name });
  const section = heading.closest("section");

  if (section === null) {
    throw new Error(`Could not find section for ${name}`);
  }

  return section;
};

describe("App", () => {
  it("renders upload guidance before a report exists", () => {
    render(<App />);

    expect(
      screen.getByRole("heading", { level: 1, name: "Busfactor2" }),
    ).toBeInTheDocument();
    expect(
      screen.getByText(
        "Upload a prepared git log to analyze commit activity and file ownership.",
      ),
    ).toBeInTheDocument();
    expect(screen.getByLabelText("Git log file")).toBeInTheDocument();
    expect(
      screen.getByText("git log --no-merges --name-status main > ~/gitlog.txt"),
    ).toBeInTheDocument();
    expect(
      screen.getByText(new RegExp(REPORT_SCHEMA_VERSION)),
    ).toBeInTheDocument();
    expect(
      screen.queryByRole("heading", { name: "Summary" }),
    ).not.toBeInTheDocument();
  });

  it("renders a report from an uploaded legacy git log", async () => {
    uploadGitLog(legacyGitLog);

    expect(
      await screen.findByText("Analyzed legacy-git-log.txt."),
    ).toBeInTheDocument();

    const summary = getSection("Summary");
    expect(within(summary).getByText("Authors")).toBeInTheDocument();
    expect(within(summary).getByText("Weeks")).toBeInTheDocument();
    expect(within(summary).getByText("Tracked files")).toBeInTheDocument();
    expect(within(summary).getByText("Risk files")).toBeInTheDocument();
    expect(within(summary).getByText("9")).toBeInTheDocument();
    expect(within(summary).getByText("8")).toBeInTheDocument();

    const weeklyTable = screen.getByRole("table", {
      name: "Weekly commits by author",
    });
    expect(within(weeklyTable).getByText("Alice Example")).toBeInTheDocument();
    expect(within(weeklyTable).getByText("Bob Example")).toBeInTheDocument();
    expect(within(weeklyTable).getByText("Cara Example")).toBeInTheDocument();
    expect(within(weeklyTable).getByText("2024-02-04")).toBeInTheDocument();
    expect(within(weeklyTable).getByText("2024-01-28")).toBeInTheDocument();

    const overall = getSection("Overall");
    expect(within(overall).getByText("9 files, 8 risky")).toBeInTheDocument();
    expect(within(overall).getByText("src/app.js")).toBeInTheDocument();
    expect(within(overall).getByText("styles/site.css")).toBeInTheDocument();
    expect(within(overall).getAllByText("yes").length).toBeGreaterThan(0);
    expect(within(overall).getAllByText("no").length).toBeGreaterThan(0);

    const tsJsCss = getSection("TS/JS/CSS");
    expect(within(tsJsCss).getByText("9 files, 8 risky")).toBeInTheDocument();
    expect(within(tsJsCss).getByText("src/feature.ts")).toBeInTheDocument();

    expect(
      within(getSection("Python")).getByText("No files in this section."),
    ).toBeInTheDocument();
    expect(
      within(getSection("Markdown")).getByText("No files in this section."),
    ).toBeInTheDocument();
  });

  it("shows an error for an empty uploaded file", async () => {
    uploadGitLog("  \n", "empty-git-log.txt");

    expect(
      await screen.findByText("The uploaded git log file is empty."),
    ).toBeInTheDocument();
    expect(
      screen.queryByRole("heading", { name: "Summary" }),
    ).not.toBeInTheDocument();
  });

  it("shows an error when uploaded text has no commits", async () => {
    uploadGitLog("not a git log", "notes.txt");

    expect(
      await screen.findByText(
        "No commits were found. Upload git log text generated by git log --no-merges --name-status main.",
      ),
    ).toBeInTheDocument();
    expect(
      screen.queryByRole("heading", { name: "Summary" }),
    ).not.toBeInTheDocument();
  });
});
